# Generated by Django 6.0.7 on 2026-07-10 10:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(db_default=uuid.UUID('ee55494b-f86f-4594-a1ea-e6b22a12045f'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('amount', models.DecimalField(decimal_places=2, max_digits='10', verbose_name='Сумма')),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='Комментарий')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_by_category', to='transactions.category', verbose_name='Категория')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_by_statys', to='transactions.status', verbose_name='Статус')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_by_sub_category', to='transactions.subcategory', verbose_name='Подкатегория')),
                ('type_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_by_type', to='transactions.typetransaction', verbose_name='Тип транзакции')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
