# Generated by Django 6.0.7 on 2026-07-13 00:40

import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_options_alter_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(db_default=uuid.UUID('bd0e24f1-1c09-44dd-b096-f98cc1f8ccdc'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sub_category',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, to='transactions.subcategory'),
        ),
    ]
