# Generated by Django 6.0.7 on 2026-07-13 23:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_created_at_alter_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(db_default=uuid.UUID('8d8f3d86-142d-40f3-add3-1995f5d27663'), editable=False, primary_key=True, serialize=False),
        ),
    ]
