# Generated by Django 6.0.7 on 2026-07-13 23:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(db_default=uuid.UUID('1a8ea64e-a4a9-47e6-8855-19da200f7d12'), editable=False, primary_key=True, serialize=False),
        ),
    ]
