# Generated by Django 6.0.7 on 2026-07-13 23:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(db_default=uuid.UUID('837bb2e4-0ab7-4ab7-922d-6239ccebd293'), editable=False, primary_key=True, serialize=False),
        ),
    ]
