# Generated by Django 6.0.7 on 2026-07-13 23:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(db_default=uuid.UUID('81d4270a-7708-4609-9978-cc9bb2e2b545'), editable=False, primary_key=True, serialize=False),
        ),
    ]
