# Generated by Django 6.0.7 on 2026-07-13 23:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(db_default=uuid.UUID('68881f6d-aae2-4011-b843-3230c1dd5b63'), editable=False, primary_key=True, serialize=False),
        ),
    ]
