# Generated by Django 6.0.7 on 2026-07-13 23:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(db_default=uuid.UUID('8b2a2dc7-e65d-45db-ace0-d8897e3d209a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
