# Generated by Django 6.0.7 on 2026-07-13 23:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_alter_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(db_default=uuid.UUID('42bc1c0f-c84e-42fc-b5c0-a37f0beec4ae'), editable=False, primary_key=True, serialize=False),
        ),
    ]
