# Generated by Django 6.0.7 on 2026-07-13 23:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_alter_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(db_default=uuid.UUID('8d71fb24-061e-4968-9f67-8183e1542b90'), editable=False, primary_key=True, serialize=False),
        ),
    ]
