# Generated by Django 6.0.7 on 2026-07-13 23:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_alter_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(db_default=uuid.UUID('21f7f71d-5c94-42a6-85af-8b102dc0f181'), editable=False, primary_key=True, serialize=False),
        ),
    ]
