# Generated by Django 6.0.7 on 2026-07-13 23:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_alter_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(db_default=uuid.UUID('c166df65-30d7-4fbe-a50a-0113acfe87da'), editable=False, primary_key=True, serialize=False),
        ),
    ]
